services:
  - type: web
    name: chocoberry
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: PORT
        value: 8080
    disk:
      name: chocoberry-data
      mountPath: /app/server/data
      sizeGB: 1
